"""
ppflx.keys.he_elgamal — key material for the he_elgamal_zkp mode.

Key material:
    secret_key.json  — shared client key {"sk", "pk"} (clients decrypt aggregates)
    public_key.json  — {"pk"} (server encrypts nothing; it verifies and aggregates)

Keys are generated by the gnark service binary so the curve arithmetic has a
single implementation.

Usage::

    python -m ppflx.keys generate he_elgamal
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from pathlib import Path

# The proof service binary, which also generates ElGamal key pairs. Set
# FL_GNARK_BINARY when the service is not checked out beside this package.
BINARY_ENV = "FL_GNARK_BINARY"
_DEFAULT_BINARY = Path(__file__).resolve().parents[2] / "zkp_gnark_service" / "gnark_service"


def gnark_binary() -> Path:
    return Path(os.environ.get(BINARY_ENV, str(_DEFAULT_BINARY)))

_HEX_POINT = re.compile(r"^[0-9a-f]{64}$")


def generate(
    secret_path: str = "keys/he_elgamal/secret_key.json",
    public_path: str = "keys/he_elgamal/public_key.json",
    overwrite: bool = False,
) -> None:
    for path in (secret_path, public_path):
        if os.path.exists(path):
            if not overwrite:
                raise FileExistsError(f"{path} already exists. Pass overwrite=True to regenerate.")
            os.remove(path)
    binary = gnark_binary()
    if not binary.exists():
        raise FileNotFoundError(
            f"{binary} not built. Build the proof service (go build -o gnark_service .) "
            f"or point {BINARY_ENV} at it."
        )
    for path in (secret_path, public_path):
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)

    result = subprocess.run(
        [str(binary), "elgamal-keygen", secret_path, public_path],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"elgamal-keygen failed: {result.stderr.strip()}")
    load_client(secret_path)
    load_server(public_path)
    print(f"[he_elgamal] Secret (shared client) key → {secret_path}")
    print(f"[he_elgamal] Public key                 → {public_path}")


def _read(path: str, what: str) -> dict:
    if not os.path.exists(path):
        raise FileNotFoundError(f"{what} not found: {path}\nRun: python -m ppflx.keys generate he_elgamal")
    with open(path) as f:
        return json.load(f)


def load_client(secret_path: str = "keys/he_elgamal/secret_key.json") -> dict:
    data = _read(secret_path, "ElGamal secret key")
    if not str(data.get("sk", "")).isdigit() or not _HEX_POINT.match(str(data.get("pk", ""))):
        raise ValueError(f"{secret_path} is not a valid ElGamal secret key file")
    return {"sk": data["sk"], "pk": data["pk"]}


def load_server(public_path: str = "keys/he_elgamal/public_key.json") -> str:
    data = _read(public_path, "ElGamal public key")
    if "sk" in data:
        raise ValueError(f"{public_path} contains a secret key; the server must only hold the public key")
    if not _HEX_POINT.match(str(data.get("pk", ""))):
        raise ValueError(f"{public_path} is not a valid ElGamal public key file")
    return data["pk"]
